version: "2.3"

services:
  # ROS Melodic
  core2-flash:
    build:
      context: ../../ 
      dockerfile: ./Dockerfile
    tty: true 
    restart: on-failure
    privileged: true
    command: ./flash_firmware.sh
