version: "2.3"

services:
  # ROS Melodic

  rosbot:
    build:
      context: ../../ 
      dockerfile: ./Dockerfile
    tty: true        
    restart: on-failure
    privileged: false
    environment:
      - "ROS_MASTER_URI=http://my-ros-master:11311"
      - "SERIAL_PORT=/dev/ttyS4" # default: ttyS1 - rosbot2.0; ttyS4 - rosbot2.0 pro
    devices:
      - "/dev/ttyS4"   # must match environment SERIAL_PORT 
    command: roslaunch rosbot_description serialbridge_only.launch
        
  my-ros-master:
    image: ros:noetic-ros-core
    restart: on-failure
    tty: true        
    command: stdbuf -o L roscore

  # ROS Noetic + ROS 2 eloquent
  bridge:
    image: ros:eloquent-ros1-bridge
    restart: on-failure
    environment:
      - "ROS_MASTER_URI=http://my-ros-master:11311"
    command: 
      - bash
      - -c
      - |
        stdbuf -o L roscore &
        ros2 run ros1_bridge dynamic_bridge

  # ROS 2 
  rviz2:
    image: husarion/rviz2-rosbot:eloquent
    restart: on-failure
    privileged: true
    environment: 
      - QT_X11_NO_MITSHM=1 
      - DISPLAY=$DISPLAY 
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: ros2 run rviz2 rviz2