version: "2.3"

services:
  # ROS Melodic
  rosbot:
    build:
      context: ../../ 
      dockerfile: ./Dockerfile
    tty: true        # docker run -t
    restart: unless-stopped
    environment:
      - "ROS_MASTER_URI=http://my-ros-master:11311"
    privileged: true
    command: 
      - bash
      - -c
      - |
        ./flash_firmware.sh
        roslaunch rosbot_description serialbridge_only.launch

  astra:
    image: husarion/astra:latest
    restart: unless-stopped
    environment:
        - "ROS_MASTER_URI=http://my-ros-master:11311"
    devices:
      - /dev/ttyUSB0
    tty: true        # docker run -t
    command: roslaunch ros_astra_camera astra.launch

  rplidar:
    image: husarion/rplidar:latest
    restart: unless-stopped
    environment:
        - "ROS_MASTER_URI=http://my-ros-master:11311"
    devices:
      - /dev/ttyUSB1
    tty: true        # docker run -t
    command: roslaunch rplidar_ros rplidar.launch

  # ROS Noetic
  my-ros-master:
    image: ros:noetic-ros-core
    restart: unless-stopped
    tty: true        # docker run -t
    command: stdbuf -o L roscore

  # ROS Noetic + ROS 2 Foxy
  bridge:
    image: ros:foxy-ros1-bridge
    restart: unless-stopped
    environment:
      - "ROS_MASTER_URI=http://my-ros-master:11311"
    command: 
      - bash
      - -c
      - |
        stdbuf -o L roscore &
        ros2 run ros1_bridge dynamic_bridge

  # ROS 2 Foxy
  rviz2:
    image: husarion/rviz2-rosbot:latest
    restart: unless-stopped
    environment: 
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: ros2 run rviz2 rviz2